### ISSUE TITLE
Firebase Rule

### ISSUE THREAD

**Issue by SaltyAom** [ycccamp/ycc-regis#4]
Firebase rule is quite necessary for securing the data which we don't want to be exposed.
I have tried update the Firebase rule as the following
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /registration/{registration} {
      allow create: if request.auth.uid != null;
      allow read, write:
        if request.auth.uid == registration
    }
  }
}
```
Which should securing the `registration` collection and is tested with uid but the weird part is, on the production it log `insufficient permission` which I'm not quite sure why.
Is our document in `registration` collection using `uid`? (But the codebase said it's using `uid`)
You might want to take a look, there's also a history in Firebase's Firestore console.

**Comment by SaltyAom** [comment]
Another weird part is, I log out the `user.uid` and can't be found in the registration collection.

**Comment by wiput1999** [comment]
Is it solved?

**Comment by wiput1999** [comment]
I think this issue has been solved
